# Generated by Django 5.2.6 on 2025-10-02 10:00

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Announcement = apps.get_model('pages', 'Announcement')
    for announcement in Announcement.objects.all():
        if not announcement.slug:
            base_slug = slugify(announcement.title)
            if not base_slug:
                base_slug = f"announcement-{announcement.id}"
            
            slug = base_slug
            counter = 1
            while Announcement.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            announcement.slug = slug
            announcement.save()


def reverse_populate_slugs(apps, schema_editor):
    # No need to reverse this
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=250),
        ),
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]